#!/bin/bash

set -ex

scriptpath="$(readlink -f "$0")"
SLIM_CFG_TOP_DIR="${scriptpath%/${0##*/}}"
SLIM_CFG_OPENWRT_BRANCH="master"
SLIM_CFG_OPENWRT_COMMIT=""
SLIM_CFG_OPENWRT_ABBREV_COMMIT=""
SLIM_CFG_OPENWRT_VERSION="19.07"
SLIM_CFG_TARGET="x86"
SLIM_CFG_ARCH="64"

SLIM_CFG_DOWNLOAD_PATH="$SLIM_CFG_TOP_DIR/downloaded"
SLIM_CFG_CLONE_PATH="$SLIM_CFG_TOP_DIR/downloaded/$SLIM_CFG_OPENWRT_BRANCH-$SLIM_CFG_OPENWRT_ABBREV_COMMIT"

if [ -z $SLIM_CFG_PROFILE ]
then
    SLIM_CFG_PROFILE="slim"
fi

echo Work with profile : $SLIM_CFG_PROFILE
SLIM_CFG_PROFILE_DIR="$SLIM_CFG_TOP_DIR/profiles/$SLIM_CFG_PROFILE"


# should override by profile
SLIM_CFG_WORK_PATH=""
SLIM_CFG_BIN_IMG_DIR=""
SLIM_CFG_PATCHES_MODULES=""
